### PR TITLE
[WIP] Code Quality Improvements #79

### PR DESCRIPTION
**Pull request by TkTech**
WIP for issue #79. Since this will be a very large PR with many very small changes, I'm pushing as I go so review can be done.

# Why

The goal of this PR is to clean up the concierge code base in preparation for the work of getting the Government of Canada changes merged back upstream and set up best-practices so we don't end up so diverged in the future.

# What

The first batch of commits will be for PEP8(+unused variables, +unused imports, +missing imports), and some small fixes with one commit per module.

The second batch of commits will be modernization for py3.6 (fstrings, typing, etc), larger logic fixes, and tests. Current code coverage by tests is at less then 15%.

### CODE REVIEW

**Comment by TkTech** [comment]
@AadSchippers the "with" means we're creating a context manager. When we leave the scope (the deindent) the file will automatically close. This includes proper handling even when exceptions are raised. It's always the preferred way to use IO objects in Python.

Py4 is 5+ years away, think we're safe keeping it for compatibility :)

**Comment by AadSchippers** [comment]
ty :)

**Comment by AadSchippers** [comment]
Great work again @TkTech, thanks.

I've got a few questions cq remarks:

- Is there any specific reason to change "is_admin" to "is_superuser"?
- Have you checked any compatibility issues regarding the version upgrades in requirements.txt?
- In requirements.txt I've noticed that both "Django==1.11" and "Django==2.0.9" are mentioned. Is that a slip of the pen or am I missing something?

**Comment by TkTech** [comment]
- `is_superuser` is part of the [django base model](https://docs.djangoproject.com/en/2.1/ref/contrib/auth/#django.contrib.auth.models.User.is_superuser) and is what django admin and other modules like `constance` will look for. `is_admin` was project-specific and identical to `is_superuser`. Since `AliasField` is no longer trivial with the removal of `virtual_only` in django 2.0 I just removed the redundant field in favor of the universal django one.
- There have been no compatibility issues so far, and everything is working as expected. Django 2.1.3 can be used once the next version of django-oidc-provider is released.
- Good catch, typo! I will fix this.

**Comment by AadSchippers** [comment]
Thanks for your contributiion @TkTech.

**Comment by AadSchippers** [comment]
Closed :P

**Pull request merged**
